services:
  nginx:
    image: nginx:1.24
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
      # localにログファイルを出力（logsコマンドで確認出来なくなるが。。あとMacが遅くなるかも）
      - ./logs/nginx:/var/log/nginx
      # dbのimageを引っ張ってきた
      - ./image:/image
    ports:
      - "80:80"
    links:
      - app
  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: golang/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
      # postされた画像をnginx用ディレクトリに書き起こすためのところ
      - ./image:/image
    init: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
  mysql:
    image: mysql:8.0
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      # macが遅くなるかも
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
  memcached:
    image: memcached:1.6
volumes:
  mysql:
